SELECT dbo.GooglePhoneLibSqlFunction('test')
SELECT dbo.GoogleFindNumbers('test')
SELECT dbo.GoogleIsNumberMatch('test')
SELECT dbo.GoogleIsValidNumber('test')
SELECT dbo.GoogleIsPossibleNumber('test')